# Generated by Django 2.2.17 on 2021-01-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20210115_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crate',
            name='slug',
        ),
        migrations.AddField(
            model_name='crate',
            name='billed',
            field=models.BooleanField(default=False, help_text='Whether this crate has been billed/emptied', verbose_name='Crate billed'),
        ),
    ]
