# Generated by Django 2.2.17 on 2021-01-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20210115_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='crate',
            name='billed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
