# Generated by Django 3.1.5 on 2021-01-15 02:08

import bartender.drinks.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_crate_billed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crate',
            name='billed_document',
            field=models.FileField(editable=False, null=True, upload_to=bartender.drinks.generators.generate_billed_document_path, verbose_name='Billing document'),
        ),
    ]
