# Generated by Django 2.2.17 on 2021-01-15 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210115_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
