# Generated by Django 2.2.17 on 2021-01-15 00:08

import bartender.users.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invite_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(default=bartender.users.generators.generate_invite_token, editable=False, max_length=4),
        ),
    ]
