# Generated by Django 3.1.5 on 2021-01-15 02:08

import bartender.users.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210115_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(default=bartender.users.generators.generate_invite_token, editable=False, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(editable=False, help_text='Telegram User ID', null=True, unique=True),
        ),
    ]
